Update Discovery ISO modal
mareklibra/facet-lib pull request #159
Opened 2020-08-20 10:01 UTC by rawagner

![Screenshot from 2020-08-20 11-54-42](https://user-images.githubusercontent.com/2078045/90755931-0a32b800-e2dc-11ea-8d59-a6c3f5c79cb1.png)

2020-08-20 11:01 UTC, jtomasek requested changes
I am getting
```Formik called `handleChange`, but you forgot to pass an `id` or `name` attribute to your input:```
when setting the ssh key via dragging or clicking the 'browse' button as well as when clicking 'clear'.

Looks pretty great btw.!

2020-08-20 11:18 UTC, jtomasek commented on src/components/clusterConfiguration/DiscoveryImageForm.tsx
> +import './discovery.css';
```suggestion
import './discoveryImageModal.css';
```

maybe?

2020-08-20 12:51 UTC, rawagner commented on src/components/clusterConfiguration/DiscoveryImageForm.tsx
> +import './discovery.css';
renamed

2020-08-20 12:51 UTC, rawagner commented on src/components/clusterConfiguration/DiscoveryImageForm.tsx
> +    <Text className="boot-order-order" component={TextVariants.small}>
fixed

2020-08-20 13:04 UTC, rawagner commented on src/components/clusterConfiguration/DiscoveryImageForm.tsx
> +  <Text className="boot-order" component="p">
Good idea, fixed

2020-08-20 13:13 UTC, rawagner commented
@jtomasek file update errors should be fixed as well. PTAL

2020-08-20 18:24 UTC, andybraren commented
It took me a minute to figure out if your screenshot was of the implementation or @nirfarkas' [design](https://marvelapp.com/prototype/78g662d/screen/71249234). 😄 This looks awesome!!

And it includes PatternFly's new file upload component!? ❤️

I see `Use HTTP Proxy` was changed to `Configure HTTPS Proxy` but that sounds fine to me too.

2020-08-21 06:12 UTC, jtomasek approved these changes

2020-08-21 06:13 UTC, merged