Revert "Merge pull request #159 from rawagner/discovery_form"
mareklibra/facet-lib pull request #164
Opened 2020-08-26 12:42 UTC by rawagner

This reverts commit 7da4ef7a981f5057a96f61d0b72f88928533a154, reversing
changes made to 3f4d12a4823d5ec72f29ab37f56ba3d2673935eb.

The new ISO modal needs to be redesigned

2020-08-26 13:53 UTC, jtomasek requested changes
Maybe we could keep the new UploadField usage + other tweaks and just put back the original Discovery flow description?

2020-08-26 17:49 UTC, andybraren commented
+1 the new functionality would be great to keep; the boot order area just needs to be adjusted.

2020-08-26 17:59 UTC, rawagner commented
OK, using mix of old and new :) 

![Screenshot from 2020-08-26 19-57-11](https://user-images.githubusercontent.com/2078045/91339310-978f7400-e7d6-11ea-8e5e-6e598c06bd3e.png)

2020-08-27 09:07 UTC, rawagner commented on src/components/clusterConfiguration/DiscoveryImageForm.tsx
> +                    during the installation.
sounds good!

2020-08-27 09:19 UTC, eranco74 approved these changes
/lgtm

2020-08-27 09:34 UTC, jtomasek approved these changes

2020-08-27 09:34 UTC, merged