Update pull secret link and description text
mareklibra/facet-lib pull request #201
Opened 2020-09-14 01:39 UTC by andybraren

OCM has a dedicated page that lets users download/copy their pull secret, so using that URL instead of the UPI instructions probably makes sense.

This PR also tweaks the description text's wording slightly to not mention OCM while the user is already within OCM. There are more updates being discussed in [MGMT-1917](https://issues.redhat.com/browse/MGMT-1917).

![image](https://user-images.githubusercontent.com/9122899/93034230-62bd5280-f607-11ea-90a3-7b75770cc7c3.png)

2020-09-14 07:54 UTC, jtomasek requested changes
Prettier check is failing, run `yarn run prettier` to fix it automatically.

2020-09-14 07:54 UTC, jtomasek commented on src/components/clusters/NewClusterPage.tsx
> +    Your Red Hat account's pull secret will be used by default. The pull secret of an account can
```suggestion
    Your Red Hat account's pull secret will be used by default. The pull secret of an account can be
```

2020-09-15 07:16 UTC, mareklibra approved these changes

2020-09-15 07:25 UTC, jtomasek approved these changes

2020-09-15 07:29 UTC, merged