MGMT-1469 Add "Hosts not showing up" to the empty state
mareklibra/facet-lib pull request #206
Opened 2020-09-16 12:52 UTC by mareklibra

![01](https://user-images.githubusercontent.com/17194943/93339700-30d90580-f82c-11ea-8d92-e809f6939972.png)

2020-09-16 12:53 UTC, mareklibra commented
Cc @andybraren

2020-09-16 15:40 UTC, andybraren approved these changes
Looks great, thank you!

2020-09-17 09:23 UTC, jtomasek requested changes
This solution will cause the modal to close if a host gets registered in the meantime. Since we're opening the modal from 2 different places now, we should move the modal opening state from `DiscoveryTroubleshootingModalButton` to `BaremetalInventory` component level, render the DiscoveryTroubleshootingModal there and pass the 'showModal/setShowModal' as props to the button

2020-09-17 13:10 UTC, mareklibra commented on src/components/hosts/HostsTable.tsx
> +      setDiscoveryHintModalOpen && [
The use from `ClusterDetail` will never come to empty state ...

2020-09-17 14:30 UTC, jtomasek approved these changes

2020-09-17 14:30 UTC, merged