MGMT-2232 Retrieve host HW requirements from backend
mareklibra/facet-lib pull request #222
Opened 2020-09-22 09:27 UTC by mareklibra

2020-09-22 09:28 UTC, mareklibra commented
![hwReqs](https://user-images.githubusercontent.com/17194943/93865477-aaf30980-fcc6-11ea-9f2f-a367dd63a518.png)

2020-09-22 09:28 UTC, mareklibra commented on src/api/utils.ts
> +export const fetchApiEndpoint = <T>({
I plan to refactor similar code at other places to use this function.

2020-09-22 09:29 UTC, mareklibra commented on src/components/clusterConfiguration/BaremetalInventory.tsx
> +  React.useEffect(() => {
I was thinking about placing this fetch at higher level in the hierarchy but so far there is no other use for it.

2020-09-24 09:00 UTC, jtomasek requested changes
Can we maybe postpone introducing `fetchApiEndpoint` helper into a separate PR which would introduce it's usage on multiple places to see how it works out?

2020-09-24 09:13 UTC, mareklibra commented on src/api/utils.ts
> +export const fetchApiEndpoint = <T>({
It's not a must to have it. The pattern repeats, so the idea was to abstract it. I understand your point, I am not big fan of over-abstracting either. So let's postpone such refactoring to a follow-up.

2020-09-24 09:22 UTC, mareklibra commented on src/api/utils.ts
> +export const fetchApiEndpoint = <T>({
removed from here

2020-09-24 09:24 UTC, mareklibra commented on src/components/clusterConfiguration/BaremetalInventory.tsx
> +      errorTitle: 'Failed to retrieve minimal host requierements',
Just out of consistency :-), but both are valid: https://english.stackexchange.com/questions/277236/what-is-the-difference-between-minimum-and-minimal

2020-09-25 08:45 UTC, jtomasek approved these changes

2020-09-25 11:03 UTC, merged