Day 2: Add Bare Metal Host feature
mareklibra/facet-lib pull request #266
Opened 2020-10-19 08:14 UTC by mareklibra

The user is able to add 1+ worker nodes in OCM.

For UX: video will follow

2020-10-20 17:11 UTC, jtomasek requested changes
There is a problem when creating `addHostCluster` from OCM cluster which uses UUID as a name as the AI API does not allow cluster name to begin with a number. Changing the 'display name' of the cluster did not help.

2020-10-20 17:11 UTC, jtomasek commented on src/components/AddBareMetalHosts/AddBareMetalHostsDialog.tsx
> +              apiVipDnsname,
Correcting these small spelling errors on API side will be quite hard to do later :/

2020-10-21 11:30 UTC, mareklibra commented on src/api/addHostsCluster.ts
> +  client.post('/add_hosts_clusters', params);
IIUC, the issue is just in naming of the endpoint. Let's move this discussion to slack and react in UI (follow-up) accordingly.
But you are right, there will never be better time to change this than now.

2020-10-21 12:47 UTC, mareklibra commented on src/components/AddBareMetalHosts/AddBareMetalHostsDialog.tsx
> +        <Alert isInline variant={AlertVariant.danger} title="Add Bare Metal Hosts failed">
done

2020-10-21 12:47 UTC, mareklibra commented on src/components/hosts/RoleCell.tsx
> +  return !forceStatic && canEditRole(clusterStatus, host.status) ? (
right, it is not needed. And recent canEditRole is already false for this clusterStatus. So: done.

2020-10-21 12:47 UTC, mareklibra commented on src/components/hosts/HostsTable.tsx
> +              forceStatic={variant != 'Cluster'}
done

2020-10-21 14:00 UTC, mareklibra commented on src/components/AddBareMetalHosts/BareMetalInventoryAddHost.tsx
> +        <Text component="p">
These are adepts for reusable components but contemplating if it is not over-killing.

2020-10-22 13:53 UTC, jtomasek approved these changes
There are several changes we should do as a follow up:
1. Render the day2 cluster as a tab within the OCM cluster detail page:
    - Remove AddBareMetalHost modal and instead the action would activate the 'scale cluster' or 'add hosts' tab in OCM cluster detail. Here we'd fetch the data and create/load the AI day 2 cluster resource.
    - Allows us to avoid showing day2 clusters from the AI clusters list
2. Implement the same (as 1.) day2 integration for AI day1 cluster
3. Backend should update the status_info for cluster in 'adding_hosts' state to something like: 'This cluster is used for adding hosts to existing cluster <name/id>
4. Improve description of 'added-to-existing-cluster' cluster status to 'Host has booted RHCOS image, please use cluster console to monitor further progress of adding this host to the cluster'

2020-10-23 07:59 UTC, mareklibra commented
@jtomasek , thanks for your comments. Avoiding modal dialog in favour of new OCM detail subtab will make the integration tighter and more user friendly. I believe transition from this PR state to the subtab will not be complicated.

2020-10-23 08:01 UTC, merged